import { Bot } from "lucide-react";

export default function AIReviewCard({
  review = "",
}) {
  return (
    <div className="rounded-3xl bg-[#111827] border border-white/10 p-10">

      <div className="flex items-center gap-4 mb-8">

        <div className="w-14 h-14 rounded-2xl bg-gradient-to-r from-cyan-500 to-blue-600 flex items-center justify-center">

          <Bot size={28}/>

        </div>

        <div>

          <h2 className="text-3xl font-black">

            AI Professional Review

          </h2>

          <p className="text-gray-400">

            Generated by CareerPilot AI

          </p>

        </div>

      </div>

      <div className="rounded-2xl bg-[#0B1120] border border-white/10 p-8">

        <p className="leading-9 whitespace-pre-wrap text-gray-300">

          {review}

        </p>

      </div>

    </div>
  );
}